name: app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/ava.png
    - assets/famicons_earth-sharp.png
    - assets/food.png
    - assets/ic_outline-lightbulb.png
    - assets/Mask group.png
    - assets/phon.png
    - assets/photo_2025-04-03_22-40-02.jpg
    - assets/photo_2025-04-03_22-40-03 (2).jpg
    - assets/photo_2025-04-03_22-40-03 (3).jpg
    - assets/photo_2025-04-03_22-40-03.jpg
    - assets/Vector.png
    - assets/ri_tree-line.png
    - assets/map.png
    - assets/card3_1.png
    - assets/card3_2.png
    - assets/card3_3.png
    - assets/card3_4.png
    - assets/card3_5.png
    - assets/card4_1.png
    - assets/card4_2.png
    - assets/card4_3.png
    - assets/card4_4.png
    - assets/card4_5.png
    - assets/card5_1.png
    - assets/card5_2.png
    - assets/card5_3.png
    - assets/card5_4.png
    - assets/card5_5.png
    - assets/card2_1.png
    - assets/card2_2.png
    - assets/card2_3.png
    - assets/card2_4.png
    - assets/card2_5.png
    - assets/class_bg.png
    - assets/place_bg.png
    - assets/food_bg.png
    - assets/facts_bg.png
    - assets/asistent.png
  fonts:
    - family: AbhayaLibre
      fonts:
        - asset: assets/fonts/AbhayaLibre-Regular.ttf
        - asset: assets/fonts/AbhayaLibre-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
